import { TripDto } from "./types/dto/common/TripDto";

export const mockTrip: TripDto = {
    id: 1,
    tripCode: "barcelona-2021",
    departureDate: "2023-08-01T00:00:00.000Z",
    arrivalDate: "2023-08-07T00:00:00.000Z",
    label: "",
    tripItems: [
        {
            dateTime: "2023-08-01T07:00:00.000Z",
            type: "restaurant",
            value: {
                id: 2,
                label: "La Pizzara",
                address: "Rambla Del Raval, 13 Local 2, 08001 Barcelona Spain",
                phone: "34671897265",
                imageUrl: null,
                website: null,
                rating: 4,
                email: null,
                mapLocation: { lat: 2.22564, long: 41.42003 },
                code: "la-pizzarra",
                avgMealPerPerson: 37.5,
                food: "italian",
            },
        },
        {
            dateTime: "2023-08-01T09:00:00.000Z",
            type: "attraction",
            value: {
                id: 17,
                label: "Prado Museum",
                about: "The Prado Museum, officially known as Museo Nacional del Prado, is the main Spanish national art museum, located in central Madrid.",
                address: "C. de Ruiz de Alarcón, 23, 28014 Madrid, Spain",
                phone: "34 913 30 28 00",
                suggestedDuration: 1,
                entryFee: 15,
                imageUrl: "http://localhost:8055/assets/2da82976-d483-4888-90d7-a128834a1f33.jpg",
                website: "https://www.museodelprado.es/en",
                type: "Art",
                rating: 4,
                reservationLink: "https://www.museodelprado.es/en",
                minAge: 12,
                email: "cav@museodelprado.es",
                mapLocation: { long: -3.69213, lat: 40.41378 },
                openingHours: {
                    from: "1970-01-01T10:00:00.000Z",
                    to: "1970-01-01T20:00:00.000Z",
                },
            },
        },
        {
            dateTime: "2023-08-01T11:00:00.000Z",
            type: "attraction",
            value: {
                id: 7,
                label: "Casa Mila",
                about: 'Casa Milà , Spanish: , popularly known as La Pedrera, Spanish; "the stone quarry") in reference to its unconventional rough-hewn appearance, is a Modernista building in Barcelona, Catalonia, Spain. It was the last private residence designed by architect Antoni Gaudí and was built between 1906 and 1912.',
                address: "Pg. de Gràcia, 92, 08008 Barcelona, Spain",
                phone: "34932142576",
                suggestedDuration: 3,
                entryFee: 27.64,
                imageUrl: "http://localhost:8055/assets/b504ce1a-3d09-4b8b-ba7f-5a2e8c5b06f2.jpg",
                website: "https://www.lapedrera.com/en",
                type: "Historical",
                rating: 2,
                reservationLink: "https://www.lapedrera.com/en/visits",
                minAge: 0,
                email: null,
                mapLocation: { long: 41.3952, lat: 2.1619 },
                openingHours: {
                    from: "1970-01-01T06:00:00.000Z",
                    to: "1970-01-01T20:00:00.000Z",
                },
            },
        },
        {
            dateTime: "2023-08-01T14:00:00.000Z",
            type: "restaurant",
            value: {
                id: 3,
                label: "NOW - Not Only Wine",
                address: "c/ Hercegovina 28 Plaza Boston, 08006 Barcelona Spain",
                phone: "34931892878",
                imageUrl: null,
                website: "https://www.notonlywine.es/",
                rating: 3,
                email: null,
                mapLocation: { lat: 41.40795, long: 41.40795 },
                code: "not-only-wine",
                avgMealPerPerson: 27,
                food: "Mediterranean",
            },
        },
        {
            dateTime: "2023-08-01T16:00:00.000Z",
            type: "attraction",
            value: {
                id: 8,
                label: "Girona Cathedral",
                about: "Girona Cathedral, also known as the Cathedral of Saint Mary of Girona (in Catalan: Catedral de Santa Maria de Girona or simply Catedral de Girona), is a Roman Catholic church located in Girona, Catalonia, Spain. It is the seat of the Roman Catholic Diocese of Girona. The cathedral's interior includes the widest Gothic nave in the world, with a width of 23 metres (75 ft), and the second-widest of any church after that of St. Peter's Basilica (for comparison, the width of the nave of Reims Cathedral is 14.65 m, Saint-Étienne de Sens, 15.25 m and 12 m, in Notre Dame de Paris). Its construction was begun in the 11th century in the Romanesque architectural style, and continued in the 13th century in the Gothic style. Of the original Romanesque edifice only the 12th-century cloister and a bell tower remain. The second bell tower was completed in the 18th century.",
                address: "Pl. de la Catedral, s/n, 17004 Girona, Spain",
                phone: "34972427189",
                suggestedDuration: 1,
                entryFee: null,
                imageUrl: "http://localhost:8055/assets/a8459237-e557-4bcb-bbcd-7e4227ea6888.jpg",
                website: null,
                type: "Religious",
                rating: 3,
                reservationLink: null,
                minAge: 0,
                email: null,
                mapLocation: { long: 41.9874, lat: 2.8262 },
                openingHours: { from: null, to: null },
            },
        },
        {
            dateTime: "2023-08-01T20:00:00.000Z",
            type: "restaurant",
            value: {
                id: 4,
                label: "Grama Laounge",
                address: "Calle de la Cruz 19, 28012 Madrid Spain",
                phone: "34912405587",
                imageUrl: null,
                website: "https://gramabar.com/",
                rating: 1,
                email: "info@gramabar.com ",
                mapLocation: { lat: -3.70299, long: 40.42048 },
                code: "grama-laounge",
                avgMealPerPerson: 11.79411,
                food: "Latin",
            },
        },
        {
            dateTime: "2023-08-02T09:00:00.000Z",
            type: "attraction",
            value: {
                id: 9,
                label: "Camp Nou",
                about: "Camp Nou, branded as Spotify Camp Nou for sponsorship reasons, is the home of La Liga club FC Barcelona since its completion in 1957. With a current seating capacity of 99,354, it is the stadium with the largest capacity in Spain and Europe, and the second largest football stadium in the world.",
                address: "C. d'Arístides Maillol, 12, 08028 Barcelona, Spain",
                phone: "34902189900",
                suggestedDuration: 3,
                entryFee: 30.75,
                imageUrl: "http://localhost:8055/assets/2f34d0c2-8dea-4b2a-8495-733ceaf9a654.jpeg",
                website: "https://www.fcbarcelona.com/en/club/facilities/spotify-camp-nou",
                type: "Sports",
                rating: 4,
                reservationLink: "https://www.fcbarcelona.com/en/tickets/camp-nou-experience",
                minAge: 12,
                email: null,
                mapLocation: { long: 41.42003, lat: 2.10272 },
                openingHours: {
                    from: "1970-01-01T07:30:00.000Z",
                    to: "1970-01-01T17:00:00.000Z",
                },
            },
        },
    ],
};
